CREATE TABLE BREAKOUT (ID  SERIAL NOT NULL, TOPIC VARCHAR(255), SUBMITTEDBYUSER_MEETUPSHORT VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE TALK (ID  SERIAL NOT NULL, TITLE VARCHAR(255), PRIMARY KEY (ID));
CREATE TABLE USERTAB (MEETUPSHORT VARCHAR(255) NOT NULL, PRIMARY KEY (MEETUPSHORT));
CREATE TABLE BREAKOUT_USERTAB (Breakout_ID BIGINT NOT NULL, likedByUsers_MEETUPSHORT VARCHAR(255) NOT NULL, PRIMARY KEY (Breakout_ID, likedByUsers_MEETUPSHORT));
ALTER TABLE BREAKOUT ADD CONSTRAINT FK_BREAKOUT_SUBMITTEDBYUSER_MEETUPSHORT FOREIGN KEY (SUBMITTEDBYUSER_MEETUPSHORT) REFERENCES USERTAB (MEETUPSHORT);
ALTER TABLE BREAKOUT_USERTAB ADD CONSTRAINT FK_BREAKOUT_USERTAB_likedByUsers_MEETUPSHORT FOREIGN KEY (likedByUsers_MEETUPSHORT) REFERENCES USERTAB (MEETUPSHORT);
ALTER TABLE BREAKOUT_USERTAB ADD CONSTRAINT FK_BREAKOUT_USERTAB_Breakout_ID FOREIGN KEY (Breakout_ID) REFERENCES BREAKOUT (ID);
